# Generated by Django 4.2.7 on 2023-11-11 01:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(editable=False)),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('top_score', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mainapp.game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('game', 'session_id'), name='one_session_per_game'),
        ),
    ]
