# Generated by Django 4.2.7 on 2023-11-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_player_top_score_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='capture_time_ms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='target_pattern',
            field=models.JSONField(default=[['up', 0]]),
            preserve_default=False,
        ),
    ]
