# Generated by Django 4.2.7 on 2023-11-12 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_game_capture_time_ms_game_target_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('pattern', models.JSONField()),
                ('player', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mainapp.player')),
            ],
        ),
    ]
